#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'sidekiq/api'

TYPE = ARGV[0]

queues = Sidekiq::Queue.all

exit 0 if queues.empty?

# e.g. source=default sample#sidekiq.queue.size=42 sample#sidekiq.queue.latency=1
queues.each do |q|
  puts "source=#{q.name} #{TYPE}#sidekiq.queue.size=#{q.size} #{TYPE}#sidekiq.queue.latency=#{q.latency}"
end
